// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVA4qJPfHo1D3Jk1VcBsoUsEcL6UQLCc',
    appId: '1:856216567897:android:4efd5597d84aed69ed7148',
    messagingSenderId: '856216567897',
    projectId: 'fir-2307c',
    databaseURL: 'https://fir-2307c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2307c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEHEt2MmRTzkvr_YV0sYqZzcLeJ-snkE',
    appId: '1:856216567897:ios:6c3568bffa15e90bed7148',
    messagingSenderId: '856216567897',
    projectId: 'fir-2307c',
    databaseURL: 'https://fir-2307c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-2307c.appspot.com',
    androidClientId: '856216567897-pgapc8todqm5kc8ev6m41detd91d9f14.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracking',
  );
}
